const JWT_USER_SECRETS = process.env.JWT_USER_SECRETS
const JWT_ADMIN_SECRETS = process.env.JWT_ADMIN_SECRETS
const MONGODB_CREDENTIALS = process.env.MONGODB_CREDENTIALS
const APP_PORT  = process.env.APP_PORT

module.exports = {
    JWT_USER_SECRETS,
    JWT_ADMIN_SECRETS,
    MONGODB_CREDENTIALS,
    APP_PORT
}